name: cron

on:
  workflow_dispatch:
  schedule:
  - cron: "* * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
        scraping_hub_key: ${{secrets.SCRAPING_HUB_KEY }}
        run: echo "The API key is:${{secrets.SCRAPING_HUB_KEY}}"

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2 # Checkout the repository content to github runner.

      - name: Setup Python Version
        uses: actions/setup-python@v2
        with:
          python-version: 3.9 # Install the python version needed

      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v2
        with:
          path: "requirements.txt"
      
      
      - name: Execute Python script # Run the app.py
        run: |
          SCRAPING_HUB_KEY=${{secrets.SCRAPING_HUB_KEY }}  python handler.py
#         run: python handler.py
