name: cron

on:
  workflow_dispatch:
  schedule:
  - cron: "* * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2 # Checkout the repository content to github runner.

      - name: Setup Python Version
        uses: actions/setup-python@v2
        with:
          python-version: 3.9 # Install the python version needed

      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v2
        with:
          path: "requirements.txt"
      
      
      - name: Execute Python script # Run the app.py
#         env:
# #           scraping_hub: ${{secrets.SCRAPING_HUB_KEY }}
        run: python handler.py
